name: main

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v3.5.2
      - name: validate coding style and functionality
        run: |
            sudo apt-get install -q -y clang-format-12
            .ci/check-format.sh
        shell: bash
